name: C CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install GCC
      run: sudo apt-get install -y gcc

    - name: Change to source directory and Compile and Run Tests
      run: |
        cd $GITHUB_WORKSPACE/c
        gcc -I ../Unity/ ../Unity/unity.c utilities_test.c utilities.c -o utilities_test
        ./utilities_test
